Repository coreos/zincati, pull requests merged in 2020-09, with the labels that each got.

#349 metrics: expose process start timestamp
  src/main.rs
Labels: area/observability, kind/enhancement

#350 docs/dev: add FleetLock protocol specs
  docs/development/fleetlock/protocol.md
  docs/usage/updates-strategy.md
Labels: area/docs, kind/cleanup

#356 Release 0.0.13
  Cargo.lock
  Cargo.toml
Labels: kind/release

#360 rpm-ostree: avoid duplicating error causes
  src/rpm_ostree/cli_deploy.rs
  src/rpm_ostree/cli_finalize.rs
  src/rpm_ostree/cli_status.rs
Labels: area/rpm-ostree, area/usability, kind/cleanup

#361 main: pretty-print critical error on termination
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: area/usability, kind/cleanup

#359 cargo: update actix to latest version
  Cargo.lock
  Cargo.toml
  src/update_agent/actor.rs
Labels: area/dependencies

#363 docs/usage: expand logging page
  docs/usage/logging.md
Labels: area/docs, kind/cleanup, kind/enhancement
