Repository coreos/zincati, pull requests merged in 2020-06, with the labels that each got.

#302 docs/update-strategy: make airlock a link
  docs/usage/updates-strategy.md
Labels: area/docs, kind/bug

#116 docs/dev: describe the Cincinnati protocol used by Fedora CoreOS
  docs/development/cincinnati/protocol.md
  docs/development/cincinnati/response.json
Labels: area/cincinnati, area/docs, kind/enhancement

#314 strategy: add metrics to track updates strategy configuration
  src/strategy/mod.rs
  src/strategy/periodic.rs
  src/weekly/mod.rs
Labels: area/observability, area/updates, kind/enhancement

#313 docs: add more references to periodic strategy section
  README.md
  docs/usage/auto-updates.md
Labels: area/docs, area/updates, kind/cleanup

#308 rpm-ostree/status: detect and handle staged deployments
  src/rpm_ostree/actor.rs
  src/rpm_ostree/cli_status.rs
  src/update_agent/actor.rs
  tests/fixtures/rpm-ostree-staged.json
Labels: area/rpm-ostree, kind/bug

#312 contrib: add monitoring mixins
  .gitignore
  contrib/monitoring-mixins/README.md
  contrib/monitoring-mixins/dashboards/dashboards.libsonnet
  contrib/monitoring-mixins/jsonnetfile.json
  contrib/monitoring-mixins/mixin.libsonnet
Labels: area/observability, kind/enhancement

#316 strategy: cleanup unused logic
  src/cincinnati/client.rs
  src/cincinnati/mod.rs
  src/rpm_ostree/cli_status.rs
  src/rpm_ostree/mock_tests.rs
  src/strategy/fleet_lock.rs
  src/strategy/immediate.rs
  src/strategy/mod.rs
  src/strategy/periodic.rs
  src/update_agent/actor.rs
Labels: area/updates, kind/cleanup

#317 strategy: uniformly use config labels
  src/strategy/fleet_lock.rs
  src/strategy/immediate.rs
  src/strategy/mod.rs
  src/strategy/periodic.rs
Labels: area/observability, area/updates, kind/cleanup

#320 Release 0.0.12
  Cargo.lock
  Cargo.toml
Labels: kind/release
