Repository coreos/zincati, pull requests merged in 2021-05, with the labels that each got.

#547 update_agent: fix logic around reboot delays
  src/update_agent/actor.rs
  src/update_agent/mod.rs
Labels: area/updates, kind/bug

#556 update_agent: reword reboot delay broadcast mesage
  src/update_agent/mod.rs
Labels: area/updates, kind/enhancement

#557 cargo/release: set sign-tag property
  Cargo.toml
Labels: kind/cleanup

#559 rpm_ostree/actor: add traces when CLI returns
  src/rpm_ostree/actor.rs
Labels: area/observability

#561 Release 0.0.21
  Cargo.lock
  Cargo.toml
Labels: kind/release

#568 dist: fix dbus configuration
  dist/dbus-1/system.d/org.coreos.zincati.conf
Labels: kind/bug

#570 update_agent: slow down end state tick cadence
  src/update_agent/mod.rs
Labels: area/updates, kind/cleanup
