Repository coreos/zincati, pull requests merged in 2021-07, with the labels that each got.

#589 lockfile: general refresh, update all openssl crates
  Cargo.lock
Labels: area/dependencies

#595 Release 0.0.22
  Cargo.lock
  Cargo.toml
Labels: kind/release

#599 rpm_ostree/deploy: block on driver registration
  src/rpm_ostree/cli_deploy.rs
Labels: area/rpm-ostree, kind/friction

#604 docs/images: update actor graph with D-Bus actor
  docs/images/zincati-actors.dot
  docs/images/zincati-actors.png
Labels: area/docs

#577 update_agent: put state behind RwLock
  src/cincinnati/mod.rs
  src/identity/mod.rs
  src/update_agent/actor.rs
  src/update_agent/mod.rs
Labels: area/updates, kind/groundwork

#611 dist/config.d/*.toml: Add missing EOL
  dist/config.d/10-auto-updates.toml
  dist/config.d/10-identity.toml
Labels: kind/cleanup

#610 update_agent: remove unused `Result`s
  src/rpm_ostree/actor.rs
  src/rpm_ostree/cli_deploy.rs
  src/update_agent/actor.rs
Labels: area/updates, kind/cleanup

#613 update_agent: put state behind `Rc` instead of `Arc`
  src/update_agent/actor.rs
  src/update_agent/mod.rs
Labels: kind/cleanup

#614 update_agent: split `state_changed` out of `UpdateAgentInfo`
  src/update_agent/actor.rs
  src/update_agent/mod.rs
Labels: area/updates, kind/cleanup
