Repository coreos/zincati, pull requests merged in 2021-04, with the labels that each got.

#514 Add new actor for D-Bus server interface
  Cargo.lock
  Cargo.toml
  Makefile
  dist/dbus-1/system.d/org.coreos.zincati.conf
  src/cli/agent.rs
  src/cli/ex.rs
  src/cli/mod.rs
  src/dbus/experimental.rs
  src/dbus/mod.rs
  src/main.rs
  src/update_agent/actor.rs
  src/update_agent/mod.rs
  tests/kola/common/libtest.sh
  tests/kola/dbus/data
  tests/kola/dbus/test-experimental.sh
  tests/kola/misc/data
Labels: kind/groundwork

#503 tests/kola: add dead-end MOTD kola test
  docs/development/testing.md
  tests/kola/server/config.fcc
  tests/kola/server/test-deadend-release.sh
Labels: area/testing, status/on-hold

#525 docs: fix "Edit this page on GitHub" links
  docs/_config.yml
Labels: area/docs

#533 Clean up error handling
  Cargo.lock
  Cargo.toml
  src/cincinnati/client.rs
  src/cincinnati/mod.rs
  src/cli/agent.rs
  src/cli/deadend.rs
  src/cli/ex.rs
  src/cli/mod.rs
  src/config/inputs.rs
  src/config/mod.rs
  src/dbus/mod.rs
  src/fleet_lock/mod.rs
  src/identity/mod.rs
  src/identity/platform.rs
  src/main.rs
  src/metrics/mod.rs
  src/rpm_ostree/actor.rs
  src/rpm_ostree/cli_deploy.rs
  src/rpm_ostree/cli_finalize.rs
  src/rpm_ostree/cli_status.rs
  src/rpm_ostree/mod.rs
  src/strategy/fleet_lock.rs
  src/strategy/immediate.rs
  src/strategy/mod.rs
  src/strategy/periodic.rs
  src/update_agent/actor.rs
  src/update_agent/mod.rs
  src/weekly/mod.rs
  src/weekly/utils.rs
Labels: area/dependencies, kind/cleanup

#534 ci: bump linting toolchain
  .github/workflows/rust.yml
  src/cincinnati/client.rs
  src/cli/agent.rs
  src/fleet_lock/mod.rs
  src/rpm_ostree/actor.rs
  src/rpm_ostree/cli_status.rs
  src/strategy/mod.rs
  src/update_agent/mod.rs
Labels: area/testing, kind/enhancement

#536 Bump tokio, actix, reqwest
  Cargo.lock
  Cargo.toml
  src/cincinnati/client.rs
  src/cincinnati/mock_tests.rs
  src/cli/agent.rs
  src/dbus/experimental.rs
  src/fleet_lock/mock_tests.rs
  src/fleet_lock/mod.rs
  src/metrics/mod.rs
  src/rpm_ostree/mock_tests.rs
  src/strategy/immediate.rs
  src/strategy/periodic.rs
Labels: area/dependencies

#524 strategy/periodic: support configuring a time zone for reboot windows
  Cargo.lock
  Cargo.toml
  docs/development/update-strategy-periodic.md
  docs/usage/updates-strategy.md
  src/config/fragments.rs
  src/config/inputs.rs
  src/strategy/fleet_lock.rs
  src/strategy/mod.rs
  src/strategy/periodic.rs
  src/weekly/mod.rs
  src/weekly/utils.rs
  tests/fixtures/00-config-sample.toml
  tests/fixtures/30-periodic-sample-non-utc.toml
  tests/fixtures/31-periodic-sample-non-utc.toml
Labels: area/usability, kind/enhancement

#542 Release 0.0.20
  Cargo.lock
  Cargo.toml
Labels: kind/release

#543 update_agent: log deploy attempt outcome
  src/update_agent/actor.rs
Labels: area/observability, kind/enhancement, kind/friction
