Repository coreos/zincati, pull requests merged in 2021-02, with the labels that each got.

#454 update-agent: expose current state via sd_notify
  dist/systemd/system/zincati.service
  src/update_agent/actor.rs
  src/update_agent/mod.rs
  tests/kola/libtest.sh
  tests/kola/misc/data
  tests/kola/misc/test-status.sh
Labels: area/observability, area/updates, kind/enhancement

#458 github/release-checklist: generate vendor tarball too
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: area/docs, kind/cleanup

#460 Release 0.0.16
  Cargo.lock
  Cargo.toml
Labels: kind/release

#463 tests/kola: fix recursive symlink
  .github/workflows/rust.yml
  tests/kola/misc/data
  tests/kola/misc/data/libtest.sh
Labels: area/testing, kind/bug

#469 Release 0.0.17
  Cargo.lock
  Cargo.toml
Labels: kind/release

#471 docs/usage/metrics: Minor link fix for Jekyll pages
  docs/usage/metrics.md
Labels: area/docs

#472 rpm-ostree: cache status to minimize daemon wakeups
  Cargo.lock
  Cargo.toml
  src/identity/mod.rs
  src/rpm_ostree/actor.rs
  src/rpm_ostree/cli_status.rs
  src/rpm_ostree/mod.rs
Labels: area/rpm-ostree, kind/enhancement

#456 cincinnati: record ignored update targets in logs and metrics
  src/cincinnati/mod.rs
  src/update_agent/actor.rs
Labels: area/observability, kind/enhancement

#474 rpm-ostree: expose metrics for status querying and caching
  src/rpm_ostree/cli_status.rs
Labels: area/observability, area/rpm-ostree, kind/enhancement

#478 update_agent: fix timestamp in status updates
  src/update_agent/actor.rs
Labels: area/observability, kind/bug

#481 update-agent: add some delay after first Cincinnati check
  src/update_agent/actor.rs
Labels: area/updates, kind/enhancement

#479 agent: Broadcast message to logged in users before rebooting
  dist/systemd/system/zincati.service
  src/update_agent/actor.rs
  src/update_agent/mod.rs
Labels: kind/groundwork
