Repository coreos/zincati, pull requests merged in 2021-03, with the labels that each got.

#486 Release 0.0.18
  Cargo.lock
  Cargo.toml
Labels: kind/release

#489 update_agent: don't consider transition into own state a "state change"
  src/update_agent/mod.rs
Labels: area/observability, kind/cleanup

#450 Register as update driver for rpm-ostree
  src/rpm_ostree/actor.rs
  src/rpm_ostree/cli_deploy.rs
  src/rpm_ostree/mod.rs
  src/update_agent/actor.rs
Labels: area/observability, area/rpm-ostree, kind/enhancement

#490 rpmostree: Use Rc for status caching
  src/rpm_ostree/actor.rs
  src/rpm_ostree/cli_status.rs
Labels: area/rpm-ostree, kind/enhancement, kind/groundwork

#488 github/release-checklist: misc updates
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: area/docs, kind/cleanup

#500 cli: make check for user more flexible
  src/cli/agent.rs
  src/cli/deadend.rs
  src/cli/mod.rs
Labels: area/usability, kind/bug

#485 update_agent: delay reboot if ongoing interactive sessions
  Cargo.toml
  docs/images/zincati-fsm.dot
  docs/images/zincati-fsm.png
  src/update_agent/actor.rs
  src/update_agent/mod.rs
Labels: area/updates, kind/new-feature

#504 release-checklist: remove extraneous words
  .github/ISSUE_TEMPLATE/release-checklist.md
Labels: area/docs, kind/cleanup

#510 Release 0.0.19
  Cargo.lock
  Cargo.toml
Labels: kind/release
